POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpraGFpbWkiLCJpZCI6IjY1MmU1NTQwYWIwNjlhMDYwNGRkMzUzZiIsImlhdCI6MTY5NzU0MTcxMH0.fseswBXd7UwRKArJ-ZrA9qSTW8S7aiu-bZc4qClOEvw

{
"title": "blogi3", 
"author": "Juuso",
"url": "http://kissa.com",
"likes": 69
}